### ISSUE TITLE
Logo with transparent background

### ISSUE THREAD

**Issue by niklaas** [coodoo-io/workhorse#10]
Please provide the logo with transparent background. This would ease integrating the logo in other resources quite a lot. :-)

**Comment by laugen** [comment]
![workhorse](https://user-images.githubusercontent.com/3902428/57249913-738aab00-7046-11e9-89c6-ba29841863c2.png)
[you are welcome](https://raw.githubusercontent.com/coodoo-io/workhorse/master/src/main/resources/workhorse.png)
