### ISSUE TITLE
A JobExecution should check its status before running

### ISSUE THREAD

**Issue by nkombouris** [coodoo-io/workhorse#13]
Workhorse ignores the status from JobExecutions onces they are loaded in memory. 

Expected behavior:
If the status of an JobExecution is changed from QUEUED to FINISHED or ABORTED the JobEngine should not run the Execution. 

Replication
* Create a Batch-Job with several JobExecution
* Update the Status from QUEUED to FINISHED or ABORTED (e.g. update jobengine_execution set status = 'FINISHED' where status = 'QUEUED' )
* Check Log if the Jobengine keeps running

**Comment by laugen** [comment]
there is no performant way to react on database changes once the job execution has entered the memory queue. one should always use the service to change the status of an job execution or to delete it.
now with https://github.com/coodoo-io/workhorse/commit/ee6a29d6febdcf38361b2154facfe7c5a8a6e345 in both cases the job execution will be dropped out of the memory queue. this is available next release and the current [snapshot](https://oss.sonatype.org/content/repositories/snapshots/io/coodoo/workhorse/1.3.1-SNAPSHOT/).
if the job execution is already running there is (currently) no way to stop it...
