### ISSUE TITLE
How to run this project

### ISSUE THREAD

**Issue by rajesh7020** [coodoo-io/workhorse#24]
which server is required for run like tomcat, jboss etc. 
This project is build on spring framework or any other framework ?

**Comment by laugen** [comment]
This library is build to run in a Java EE Container like a Wildfly and is based on EJB and JPA.
We are currently releasing a Version based on CDI, so you can use it on any Java system pus it is independent of a SQL persistence. Please have a look here: https://github.com/coodoo-workhorse/workhorse

**Comment by rajesh7020** [comment]
When i run jar then i got this message: - no main manifest attribute, in workhorse.jar
How to setup database configuration and also run can you please provide setup readme file. So, i can get idea to run this project
